# Generated by Django 4.2.6 on 2023-10-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('category_desc', models.TextField()),
                ('hygiene_score', models.SmallIntegerField()),
                ('google_review_score', models.FloatField(null=True)),
                ('google_review_count', models.PositiveIntegerField()),
                ('google_place_id', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanbites_api.placedetail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanbites_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanbites_api.placedetail')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleanbites_api.user')),
            ],
        ),
    ]
