# Generated by Django 4.2.6 on 2023-10-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanbites_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placedetail',
            options={'ordering': ['business_name']},
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
