# Generated by Django 4.2.6 on 2023-11-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanbites_api', '0003_alter_placedetail_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placereview',
            old_name='user_id',
            new_name='user',
        ),
    ]
