# Generated by Django 4.2.6 on 2023-11-06 13:35

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanbites_api', '0004_rename_user_id_placereview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedetail',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]


