# Generated by Django 4.2.6 on 2023-11-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanbites_api', '0006_add_triagram_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedetail',
            name='search_vector',
        ),
    ]
