# Generated by Django 4.2.6 on 2023-11-06 15:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanbites_api', '0008_BTreeGinIndex_Ext'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placedetail',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category_desc', 'business_name', 'city'], name='searchPlaceIdx'),
        ),
    ]
