# Generated by Django 4.2.6 on 2023-11-07 23:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanbites_api', '0013_map_placedetail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedetail',
            name='categories',
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='categoryIdx'),
        ),
    ]
